server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: warehouse-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/warehouses/**
        - id: product-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/products/**